### ISSUE TITLE
Allow actions to fail without stopping the git operation

### ISSUE THREAD

**Issue by sebastianfeldmann** [captainhookphp/captainhook#197]
The idea is to allow specific `Actions`  to fail by adding a `settings`  section to `Actions`

```
  "actions": [
    {
       "action": "some action to execute",
       "options": {
         "option1": "value1"
       },
       "settings": {
         "allow-failure": true,
         "execute-async": true (just an idea for now),
         "and maybe some other stuff": "we can think  about"
       }
  ]
```

We should be able to define defaults in the `Config` settings section.

```
{
  "settings": {
    "allow-failure": true,
    "execute-async": false (just an idea for now),
    "anything we come up with": "can have default values here"
  }
}
```

### Todo

- [x] Change `Config\Action` class
- [x] Change `Config\Action` tests and test files
- [x] Change `Config` class
- [x] Change `Config` class tests and test files
- [x] Change Runners to check `Config` / `Action` settings before executing

Initial idea by @alfredbez 
Related pull request https://github.com/captainhookphp/captainhook/pull/196

**Comment by sebastianfeldmann** [comment]
I just released version 5.14.0 with the new settings. A more detailed description can be found on the release [page](https://github.com/captainhookphp/captainhook/releases/tag/5.14.0).

**Comment by alfredbez** [comment]
Many thanks for the fast feedback 🚀 

I'm unsure if I'm doing something wrong or if there is an issue either in the documentation of the new feature or in the future itself.

Your code example shows that the new flag can be added to the `settings` section, but the code and also the test reads it from `config`:
* https://github.com/captainhookphp/captainhook/blob/0d44a6f32b2aee78c41371753896e080312f9423/tests/files/config/valid-with-conditions.json#L24-L26
* https://github.com/captainhookphp/captainhook/blob/0d44a6f32b2aee78c41371753896e080312f9423/src/Config/Factory.php#L179-L180

Can you clarify that?

Bonus point: It would be awesome to print the error message even if the action is allowed to fail.

A fix for both things I mentioned can look like this:
```diff
diff --git a/src/Config/Factory.php b/src/Config/Factory.php
index c1d4c85..abfcbce 100644
--- a/src/Config/Factory.php
+++ b/src/Config/Factory.php
@@ -176,8 +176,8 @@ private function configureHook(Config\Hook $config, array $json): void
             $conditions = isset($actionJson['conditions']) && is_array($actionJson['conditions'])
                         ? $actionJson['conditions']
                         : [];
-            $settings   = isset($actionJson['config']) && is_array($actionJson['config'])
-                        ? $actionJson['config']
+            $settings   = isset($actionJson['settings']) && is_array($actionJson['settings'])
+                        ? $actionJson['settings']
                         : [];
             $config->addAction(new Config\Action($actionJson['action'], $options, $conditions, $settings));
         }
diff --git a/src/Runner/Hook.php b/src/Runner/Hook.php
index 8f323f4..1307779 100644
--- a/src/Runner/Hook.php
+++ b/src/Runner/Hook.php
@@ -342,6 +342,10 @@ private function handleAction(Config\Action $action): void
             $this->io->write('<info>done</info>', true);
         } catch (Exception  $e) {
             $this->io->write('<error>failed</error>', true);
+            $errorMessage = $action->getOptions()->get('error', false);
+            if (!$errorMessage) {
+                $this->io->write($errorMessage, true);
+            }
             if (!$action->isFailureAllowed($this->config->isFailureAllowed())) {
                 throw $e;
             }
```

**Comment by sebastianfeldmann** [comment]
You are absolutely right, I mixed up the `json` indexes and the `object property` name.
Definitely not a smart decision to call them `settings` in code but `config` in json. 

So I fixed the mismatch in version 5.14.1.

You should use `config` within your configuration file.

**Comment by alfredbez** [comment]
Thanks for clarification 👍 

Regarding the error message: Would you be open for a PR that adds something like this?
```diff
--- a/src/Config/Action.php
+++ b/src/Config/Action.php
@@ -23,6 +23,16 @@
  */
 class Action
 {
+    public const STATE_NOT_EXECUTED_YET = 1;
+    public const STATE_SKIPPED = 2;
+    public const STATE_SUCCESSFULLY_EXECUTED = 3;
+    public const STATE_FAILED = 4;
+
+    /**
+     * @var self::STATE_*
+     */
+    private int $currentState;
+
     /**
      * Action php class, php static method, or cli script
      *
@@ -74,6 +84,23 @@ public function __construct(string $action, array $options = [], array $conditio
         $this->setupOptions($options);
         $this->setupConditions($conditions);
         $this->setupSettings($settings);
+        $this->setCurrentState(self::STATE_NOT_EXECUTED_YET);
+    }
+
+    /**
+     * @param self::STATE_* $state
+     */
+    public function setCurrentState(int $state): void
+    {
+        $this->currentState = $state;
+    }
+
+    /**
+     * @return self::STATE_*
+     */
+    public function getCurrentState(): int
+    {
+        return $this->currentState;
     }

     /**
diff --git a/src/Runner/Hook.php b/src/Runner/Hook.php
index 8f323f4..5b2286e 100644
--- a/src/Runner/Hook.php
+++ b/src/Runner/Hook.php
@@ -314,6 +314,7 @@ private function executeFailAfterAllActions(array $actions): void
     private function handleAction(Config\Action $action): void
     {
         if ($this->shouldSkipActions()) {
+            $action->setCurrentState(Config\Action::STATE_SKIPPED);
             $this->io->write(
                 $this->formatActionOutput($action->getAction()) . ': <comment>deactivated</comment>',
                 true
@@ -324,6 +325,7 @@ private function handleAction(Config\Action $action): void
         $this->io->write(' - <fg=blue>' . $this->formatActionOutput($action->getAction()) . '</> : ', false);

         if (!$this->doConditionsApply($action->getConditions())) {
+            $action->setCurrentState(Config\Action::STATE_SKIPPED);
             $this->io->write('<comment>skipped</comment>', true);
             return;
         }
@@ -333,14 +335,17 @@ private function handleAction(Config\Action $action): void
         // The beforeAction() method may indicate that the current and all
         // remaining actions should be skipped. If so, return here.
         if ($this->shouldSkipActions()) {
+            $action->setCurrentState(Config\Action::STATE_SKIPPED);
             return;
         }

         try {
             $execMethod = self::getExecMethod(Util::getExecType($action->getAction()));
             $this->{$execMethod}($action);
+            $action->setCurrentState(Config\Action::STATE_SUCCESSFULLY_EXECUTED);
             $this->io->write('<info>done</info>', true);
         } catch (Exception  $e) {
+            $action->setCurrentState(Config\Action::STATE_FAILED);
             $this->io->write('<error>failed</error>', true);
             if (!$action->isFailureAllowed($this->config->isFailureAllowed())) {
                 throw $e;
```

That would allow us to create a Plugin which prints the error message in the `afterAction` if the action failed. I think this can be beneficial to other scenarios, too.

Otherwise, we would either need to use [`composer-patches`](https://github.com/cweagans/composer-patches) or overwrite the `Regex` action like so:
```php
use CaptainHook\App\Config;
use CaptainHook\App\Console\IO;
use CaptainHook\App\Exception\ActionFailed;
use SebastianFeldmann\Git\Repository;

class Regex extends \CaptainHook\App\Hook\Message\Action\Regex
{
    public function execute(Config $config, IO $io, Repository $repository, Config\Action $action): void
    {
        try {
            parent::execute($config, $io, $repository, $action);
        } catch (ActionFailed $exception) {
            $io->write('<error>failed</error>');
            $io->write($exception->getMessage());
        }
    }
}
```

**Comment by sebastianfeldmann** [comment]
The error should still be visible but you are right the error exception message is not displayed anymore.

I think tracking the state of the executed action is not enough. You would have to keep tabs on the original exception message as well to print it in any `afterAction` plugin.

I think it would make sense to display the error messages anyway so we should store the allowed error messages and after executing all actions display all occurred errors.

**Comment by sebastianfeldmann** [comment]
I just released version `5.14.2` that displays the errors even if the failure is not killing the got command.

**Comment by norgeindian** [comment]
@sebastianfeldmann , I have an action (let's call it "my-action") in my `captainhook.json`, which I would like to "disable" in my current project. So I added the following to my `captainhook.config.json`:

```
    "pre-push": {
        "actions": [
            {
                "action": "composer run my-action",
                "options": [],
                "conditions": [],
                "config": {
                    "allow-failure": true
                }
            }
        ]
    }
```

In the original `captainhook.json`, I have the following:

```
    "pre-push": {
        "enabled": true,
        "actions": [
            {
                "action": "composer run phpcs",
                "options": [],
                "conditions": [
                    {
                        "exec": "or",
                        "args": [
                            {
                                "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileChanged\\OfType",
                                "args": [
                                    "php"
                                ]
                            },
                            {
                                "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileChanged\\OfType",
                                "args": [
                                    "phtml"
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "action": "composer run phpstan",
                "options": [],
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileChanged\\OfType",
                        "args": [
                            "php"
                        ]
                    }
                ]
            },
            {
                "action": "composer run my-action",
                "options": [],
                "conditions": []
            }
        ]
    },
```

Unfortunately, the failing of "my-action" still stops the push.
When I add the "allow-failure" flag in the original `captainhook.json`, the action is ignored and the push works.
I followed http://captainhook.info/php/configure.html#:~:text=from%20version%20control%20%3B)-,Action%20settings,-You%20can%20also here, but it seems as if I'm doing something wrong.
Could you give me a hint?

**Comment by sebastianfeldmann** [comment]
`captainhook.config.json` is only to overwrite `config` settings not actions.
You can add a custom setting

```json
{
  "config": {
    "custom": {
      "ex-action": false
    }
  }
}
```

The original `captainhook.json` looks like this and includes the condition
```json
{
  "config": {
    "custom": {
      "ex-action": true
    }
  },
  "pre-push": {
    "enabled": true,
    "actions": [
      {
        "action": "my-action",
        "conditions": [
          {
            "exec": "\\CaptainHook\\App\\Hook\\Condition\\Config\\CustomValueIsTruthy",
            "args": [
              "ex-action"
            ]
          }
        ]
     }
  }
}
```

The `local.config` overwrites the custom value to false and then the `Condition` blocks the action from being executed.

**Comment by norgeindian** [comment]
@sebastianfeldmann , thanks for the fast reply, as always.
Sorry, my mistake, I had the feeling, that the section "Action settings" of the documentation belongs to "Overwrite settings
" and thought, that this is possible in the `captainhook.config.json`
